apiVersion: v2
name: kubeloop
description: KubeLoop control plane and independently scalable tunnel data plane
type: application
version: 4.0.0
appVersion: "v4.0.0"
kubeVersion: ">=1.25.0-0"
home: https://github.com/fqix/kube-loop
sources:
  - https://github.com/fqix/kube-loop
