//go:build linux

package platform

import (
	"context"
	"fmt"
	"net"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/fqix/kube-loop/internal/protocol/sessionspec"
)

const (
	resolvedDropIn = "/etc/systemd/resolved.conf.d/90-kubeloop.conf"
	linuxDNSMarker = "# Generated by KubeLoop"
)

func ApplyDNS(_ string, dns sessionspec.DNSMeta) error {
	seen := make(map[string]struct{})
	domains := make([]string, 0, len(dns.Search)+len(dns.Domains))
	for _, domain := range dns.Search {
		if domain != "" {
			seen[domain] = struct{}{}
			domains = append(domains, domain)
		}
	}
	for _, domain := range dns.Domains {
		routeOnly := "~" + domain
		if _, ok := seen[domain]; domain == "" || ok {
			continue
		}
		if _, ok := seen[routeOnly]; !ok {
			seen[routeOnly] = struct{}{}
			domains = append(domains, routeOnly)
		}
	}
	// ResolveUnicastSingleLabel forwards bare names (e.g. "echo") to DNS= so the
	// local dnsSearchProxy can apply Kubernetes search suffixes. Without it,
	// some runners return SERVFAIL/"server misbehaving" for single-label lookups
	// even when FQDN split-DNS works.
	content := fmt.Sprintf(
		"%s\n[Resolve]\nDNS=%s:%d\nDomains=%s\nDNSSEC=no\nDNSOverTLS=no\nResolveUnicastSingleLabel=yes\n",
		linuxDNSMarker, dns.Listen, dns.Port, strings.Join(domains, " "),
	)
	if err := os.MkdirAll(filepath.Dir(resolvedDropIn), 0o750); err != nil {
		return err
	}
	if existing, err := os.ReadFile(resolvedDropIn); err == nil &&
		!strings.Contains(string(existing), linuxDNSMarker) {
		return fmt.Errorf("%s is not owned by KubeLoop", resolvedDropIn)
	}
	if err := os.WriteFile(resolvedDropIn, []byte(content), 0o600); err != nil {
		return err
	}
	if err := os.Chmod(resolvedDropIn, 0o600); err != nil {
		return fmt.Errorf("secure resolved drop-in: %w", err)
	}
	reloadResolved()
	return nil
}

func RestoreDNS(_ string, _ sessionspec.DNSMeta) error {
	content, err := os.ReadFile(resolvedDropIn)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !strings.Contains(string(content), linuxDNSMarker) {
		return nil
	}
	if err := os.Remove(resolvedDropIn); err != nil && !os.IsNotExist(err) {
		return err
	}
	reloadResolved()
	return nil
}

func reloadResolved() {
	// Drop-in changes require a reload; flush-caches alone does not re-read conf.d.
	// Bound the wait so a stuck systemctl cannot wedge the helper unix RPC.
	// Do not restart: restart races the next TUN/auto_redirect bring-up on CI and
	// has caused "timed out waiting for sing-box controller" flakes.
	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()
	_ = exec.CommandContext(ctx, "systemctl", "reload", "systemd-resolved").Run()
	flushCtx, flushCancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer flushCancel()
	_ = exec.CommandContext(flushCtx, "resolvectl", "flush-caches").Run()
}

// ApplyLinkDNS configures systemd-resolved on the TUN interface. Per-link search
// domains are more reliable for single-label names than global drop-in Domains=
// alone on GitHub Actions runners.
func ApplyLinkDNS(tunAddress string, dns sessionspec.DNSMeta) error {
	iface, err := ifaceNameForTUN(tunAddress)
	if err != nil {
		return err
	}
	server := fmt.Sprintf("%s:%d", dns.Listen, dns.Port)
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := exec.CommandContext(ctx, "resolvectl", "dns", iface, server).Run(); err != nil {
		return fmt.Errorf("resolvectl dns %s: %w", iface, err)
	}

	seen := make(map[string]struct{})
	domains := make([]string, 0, len(dns.Search)+len(dns.Domains))
	add := func(domain string) {
		domain = strings.TrimSpace(domain)
		if domain == "" {
			return
		}
		if _, ok := seen[domain]; ok {
			return
		}
		seen[domain] = struct{}{}
		domains = append(domains, domain)
	}
	for _, domain := range dns.Search {
		add(domain)
	}
	for _, domain := range dns.Domains {
		routeOnly := "~" + strings.TrimPrefix(domain, "~")
		if _, ok := seen[domain]; ok {
			continue
		}
		if _, ok := seen[strings.TrimPrefix(domain, "~")]; ok {
			continue
		}
		add(routeOnly)
	}
	if len(domains) > 0 {
		args := append([]string{"domain", iface}, domains...)
		if err := exec.CommandContext(ctx, "resolvectl", args...).Run(); err != nil {
			return fmt.Errorf("resolvectl domain %s: %w", iface, err)
		}
	}
	_ = exec.CommandContext(ctx, "resolvectl", "default-route", iface, "false").Run()
	_ = exec.CommandContext(ctx, "resolvectl", "flush-caches").Run()
	return nil
}

func RestoreLinkDNS(tunAddress string) error {
	iface, err := ifaceNameForTUN(tunAddress)
	if err != nil {
		return nil
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_ = exec.CommandContext(ctx, "resolvectl", "revert", iface).Run()
	return nil
}

func ifaceNameForTUN(tunAddress string) (string, error) {
	want, err := tunHostAddr(tunAddress)
	if err != nil {
		return "", err
	}
	ifaces, err := net.Interfaces()
	if err != nil {
		return "", err
	}
	for _, iface := range ifaces {
		addrs, err := iface.Addrs()
		if err != nil {
			continue
		}
		for _, addr := range addrs {
			ipNet, ok := addr.(*net.IPNet)
			if !ok || ipNet.IP == nil {
				continue
			}
			ip, ok := netip.AddrFromSlice(ipNet.IP.To4())
			if !ok {
				ip, ok = netip.AddrFromSlice(ipNet.IP)
			}
			if ok && ip == want {
				return iface.Name, nil
			}
		}
	}
	return "", fmt.Errorf("no interface for TUN address %s", tunAddress)
}

func tunHostAddr(tunAddress string) (netip.Addr, error) {
	if prefix, err := netip.ParsePrefix(tunAddress); err == nil {
		return prefix.Addr(), nil
	}
	return netip.ParseAddr(strings.TrimSpace(tunAddress))
}

func CleanupRoutes(routes []string) {
	ip, err := exec.LookPath("ip")
	if err != nil {
		for _, candidate := range []string{"/sbin/ip", "/usr/sbin/ip"} {
			if info, statErr := os.Stat(candidate); statErr == nil && info.Mode().IsRegular() {
				ip = candidate
				break
			}
		}
	}
	if ip == "" {
		return
	}
	for _, route := range routes {
		_ = exec.Command(ip, "route", "del", route).Run()
	}
}
