//go:build darwin

package platform

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/netip"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	dnsprotocol "github.com/fqix/kube-loop/internal/protocol/dns"
	"github.com/fqix/kube-loop/internal/protocol/sessionspec"
)

const (
	darwinDNSKey       = "State:/Network/Service/io.kubeloop/DNS"
	darwinDNSSearchKey = "State:/Network/Service/io.kubeloop.search/DNS"
	resolverDir        = "/etc/resolver" // Only used to clean up pre-Dynamic Store installations.
	dnsMarker          = "# Generated by KubeLoop"
	searchBackupFile   = "search-domains.bak.json"
)

type darwinDNS struct {
	legacyResolverDir string
	run               func(name, input string, args ...string) ([]byte, error)
}

func newDarwinDNS() darwinDNS {
	return darwinDNS{legacyResolverDir: resolverDir, run: runDarwinDNSCommand}
}

func ApplyLinkDNS(string, sessionspec.DNSMeta) error { return nil }
func RestoreLinkDNS(string) error                    { return nil }

func ApplyDNS(workDir string, dns sessionspec.DNSMeta) error {
	return newDarwinDNS().apply(workDir, dns)
}

func RestoreDNS(workDir string, _ sessionspec.DNSMeta) error {
	return newDarwinDNS().restore(workDir)
}

func (d darwinDNS) apply(workDir string, dns sessionspec.DNSMeta) error {
	// Validate before changing existing state: scutil accepts a command language.
	if err := validateDarwinDNS(dns); err != nil {
		return err
	}
	if err := d.cleanupLegacy(workDir); err != nil {
		return err
	}
	if err := d.set(darwinDNSKey, dns, dns.Domains, false); err != nil {
		return err
	}
	var err error
	if len(dns.Search) == 0 {
		err = d.remove(darwinDNSSearchKey)
	} else {
		err = d.set(darwinDNSSearchKey, dns, dns.Search, true)
	}
	if err != nil {
		return errors.Join(err, d.restore(workDir))
	}
	d.flush()
	return nil
}

func validateDarwinDNS(dns sessionspec.DNSMeta) error {
	address, err := netip.ParseAddr(dns.Listen)
	if err != nil || address.Zone() != "" || address.IsUnspecified() {
		return fmt.Errorf("invalid DNS listen address %q", dns.Listen)
	}
	if dns.Port < 1 || dns.Port > 65535 || dns.Ndots < 0 || dns.Ndots > 15 {
		return fmt.Errorf("invalid DNS port or ndots")
	}
	if len(dns.Domains) == 0 {
		return fmt.Errorf("DNS match domains are required")
	}
	for _, domains := range [][]string{dns.Domains, dns.Search} {
		for _, domain := range domains {
			if !dnsprotocol.ValidClusterDomain(domain) {
				return fmt.Errorf("invalid DNS domain %q", domain)
			}
		}
	}
	return nil
}

func (d darwinDNS) set(key string, dns sessionspec.DNSMeta, domains []string, search bool) error {
	var script strings.Builder
	script.WriteString("d.init\n")
	fmt.Fprintf(&script, "d.add ServerAddresses * %s\nd.add ServerPort # %d\n", dns.Listen, dns.Port)
	fmt.Fprintf(&script, "d.add Options ndots:%d\n", dns.Ndots)
	fmt.Fprintf(&script, "d.add SupplementalMatchDomains * %s\n", strings.Join(domains, " "))
	script.WriteString("d.add SupplementalMatchOrders * #")
	for index := range domains {
		fmt.Fprintf(&script, " %d", 100000+index)
	}
	script.WriteByte('\n')
	if search {
		// configd promotes supplemental domains into the system search list.
		// A separate entry keeps routing-only suffixes (e.g. svc) out of it.
		script.WriteString("d.add SupplementalMatchDomainsNoSearch # 0\n")
	} else {
		script.WriteString("d.add SupplementalMatchDomainsNoSearch # 1\n")
	}
	fmt.Fprintf(&script, "set %s\nquit\n", key)
	output, err := d.run("/usr/sbin/scutil", script.String())
	if err != nil {
		return fmt.Errorf("set DNS Dynamic Store key %s: %w: %s", key, err, strings.TrimSpace(string(output)))
	}
	// scutil can report command errors on stdout while exiting successfully.
	if message := strings.TrimSpace(string(output)); message != "" {
		return fmt.Errorf("set DNS Dynamic Store key %s: %s", key, message)
	}
	return nil
}

func (d darwinDNS) restore(workDir string) error {
	err := errors.Join(d.remove(darwinDNSKey), d.remove(darwinDNSSearchKey), d.cleanupLegacy(workDir))
	d.flush()
	return err
}

func (d darwinDNS) remove(key string) error {
	output, err := d.run("/usr/sbin/scutil", "remove "+key+"\nquit\n")
	if err != nil {
		return fmt.Errorf("remove DNS Dynamic Store key %s: %w: %s", key, err, strings.TrimSpace(string(output)))
	}
	message := strings.TrimSpace(string(output))
	if message != "" && message != "No such key" {
		return fmt.Errorf("remove DNS Dynamic Store key %s: %s", key, message)
	}
	return nil
}

func (d darwinDNS) cleanupLegacy(workDir string) error {
	return errors.Join(d.sweepResolvers(), d.restoreLegacySearch(workDir))
}

func (d darwinDNS) sweepResolvers() error {
	entries, err := os.ReadDir(d.legacyResolverDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if !entry.Type().IsRegular() {
			continue
		}
		path := filepath.Join(d.legacyResolverDir, entry.Name())
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		if strings.HasPrefix(string(content), dnsMarker+"\n") {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

func (d darwinDNS) restoreLegacySearch(workDir string) error {
	path := filepath.Join(workDir, searchBackupFile)
	content, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	var backup map[string][]string
	if err := json.Unmarshal(content, &backup); err != nil {
		return fmt.Errorf("read legacy search domain backup: %w", err)
	}
	for service, domains := range backup {
		args := []string{"-setsearchdomains", service}
		if len(domains) == 0 {
			args = append(args, "Empty")
		} else {
			args = append(args, domains...)
		}
		if output, err := d.run("/usr/sbin/networksetup", "", args...); err != nil {
			return fmt.Errorf("restore search domains for %s: %w: %s", service, err, strings.TrimSpace(string(output)))
		}
	}
	return os.Remove(path)
}

func (d darwinDNS) flush() {
	_, _ = d.run("/usr/bin/dscacheutil", "", "-flushcache")
	_, _ = d.run("/usr/bin/killall", "", "-HUP", "mDNSResponder")
}

func runDarwinDNSCommand(name, input string, args ...string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	// Callers supply fixed system tool paths and validated DNS data, never a shell command.
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Stdin = strings.NewReader(input)
	return cmd.CombinedOutput()
}

func CleanupRoutes(routes []string) {
	for _, raw := range routes {
		prefix, err := netip.ParsePrefix(raw)
		if err != nil {
			continue
		}
		prefix = prefix.Masked()
		if prefix.Bits() == prefix.Addr().BitLen() {
			//nolint:gosec // prefix was parsed as netip.Prefix and is passed as a single argument.
			_ = exec.Command("/sbin/route", "-n", "delete", "-host", prefix.Addr().String()).Run()
		} else {
			//nolint:gosec // prefix was parsed as netip.Prefix and is passed as a single argument.
			_ = exec.Command("/sbin/route", "-n", "delete", "-net", prefix.String()).Run()
		}
	}
}
